version: '3.8'

services:
  redis:
      image: redis
      restart: always
      ports:
        - '6379:6379'
      expose: 
      - 6379
      volumes:
      - "redis:/data"
      networks:
        app_net:
          ipv4_address: 172.16.238.10
      env_file:
      - ./job_parser/.env

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./job_parser/.env
    ports:
      - 5432:5432
    restart: always
    expose: 
    - 5432
    networks:
      app_net:
        ipv4_address: 172.16.238.11

  
  django:
    build:
      context: ./job_parser
      dockerfile: Dockerfile
    command: gunicorn job_parser.wsgi:application --bind 0.0.0.0:8000
    expose: 
    - 8000
    env_file:
      - ./job_parser/.env
    volumes:
      - static_volume:/home/job_parser/django/staticfiles
      - media_volume:/home/job_parser/django/mediafiles
    networks:
      app_net:
        ipv4_address: 172.16.238.12
    depends_on: 
    - redis
    - db

  nginx:
    build: ./job_parser/nginx
    ports:
    - 1337:80
    depends_on: 
    - django
    volumes:
      - static_volume:/home/job_parser/django/staticfiles
      - media_volume:/home/job_parser/django/mediafiles
    networks:
      app_net:
        ipv4_address: 172.16.238.13

  
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    expose: 
    - 8080
    env_file:
        - ./job_parser/.env
    networks:
      app_net:
        ipv4_address: 172.16.238.14

volumes:
  postgres_data:
  static_volume:
  media_volume:
  redis:

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
