version: '3.8'

services:
  django:
    build:
      context: ./job_parser
      dockerfile: Dockerfile
    command: gunicorn job_parser.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./job_parser/.env
    volumes:
      - static_volume:/home/job_parser/django/staticfiles
      - media_volume:/home/job_parser/django/mediafiles
    networks:
      app_net:
        ipv4_address: 172.16.238.13
    depends_on: 
    - cache
    - broker
    - db

  cache:
      image: redis
      restart: always
      volumes:
      - redis:/data/cache
      networks:
        app_net:
          ipv4_address: 172.16.238.10
      env_file:
      - ./job_parser/.env
      ports:
        - 6379:6379
  
  broker:
      image: redis
      restart: always
      volumes:
      - redis:/data/broker
      networks:
        app_net:
          ipv4_address: 172.16.238.11
      env_file:
      - ./job_parser/.env
      ports:
        - 6380:6379

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./job_parser/.env
    ports:
      - 5432:5432
    restart: always
    networks:
      app_net:
        ipv4_address: 172.16.238.12

  celery:
    build: ./job_parser
    command: celery -A job_parser worker -l info
    volumes:
      - ./job_parser:/usr/src/app
    env_file:
      - ./job_parser/.env
    depends_on:
      - django
      - broker
    networks:
      app_net:
        ipv4_address: 172.16.238.14
  
  celery-beat:
    build: ./job_parser
    command: celery -A job_parser beat -l info
    volumes:
      - ./job_parser:/usr/src/app
    env_file:
      - ./job_parser/.env
    depends_on:
      - broker
    networks:
      app_net:
        ipv4_address: 172.16.238.15

  nginx:
    build: ./job_parser/nginx
    ports:
    - 1337:80
    depends_on: 
    - django
    volumes:
      - static_volume:/home/job_parser/django/staticfiles
      - media_volume:/home/job_parser/django/mediafiles
    networks:
      app_net:
        ipv4_address: 172.16.238.16

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    env_file:
        - ./job_parser/.env
    networks:
      app_net:
        ipv4_address: 172.16.238.17

volumes:
  postgres_data:
  static_volume:
  media_volume:
  redis:

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
