# Generated by Django 4.1.5 on 2023-01-27 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_id", models.CharField(max_length=50, unique=True)),
                (
                    "city",
                    models.CharField(max_length=50, unique=True, verbose_name="Город"),
                ),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
            },
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("title", models.CharField(max_length=250, verbose_name="Вакансия")),
                (
                    "salary_from",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Зарплата от"
                    ),
                ),
                (
                    "salary_to",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Зарплата до"
                    ),
                ),
                ("company", models.CharField(max_length=250, verbose_name="Компания")),
                (
                    "description",
                    models.TextField(
                        max_length=5000, null=True, verbose_name="Описание вакансии"
                    ),
                ),
                ("city", models.CharField(max_length=250, verbose_name="Город")),
                (
                    "published_at",
                    models.DateField(auto_now_add=True, verbose_name="Дата публикации"),
                ),
                (
                    "favourite",
                    models.BooleanField(default=False, verbose_name="Избраное"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.profile",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вакансия",
                "verbose_name_plural": "Вакансии",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="FavouriteVacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Избранная вакансия",
                "verbose_name_plural": "Избранные вакансии",
            },
        ),
    ]
