# Generated by Django 4.1.5 on 2023-02-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="favouritevacancy",
            name="black_list",
            field=models.BooleanField(default=False, verbose_name="Черный список"),
        ),
        migrations.AlterField(
            model_name="city",
            name="city_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
