# Generated by Django 4.1.5 on 2023-01-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="favouritevacancy",
            name="title",
            field=models.CharField(default=1, max_length=250, verbose_name="Вакансия"),
            preserve_default=False,
        ),
    ]
