# Generated by Django 4.1.5 on 2023-01-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="city",
            field=models.CharField(max_length=250, verbose_name="Город"),
        ),
    ]
