# Generated by Django 4.1.5 on 2023-03-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancyscraper",
            name="published_at",
            field=models.DateField(null=True, verbose_name="Дата публикации"),
        ),
    ]
