# Generated by Django 4.1.5 on 2023-02-04 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("parser", "0002_favouritevacancy_black_list_alter_city_city_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favouritevacancy",
            name="black_list",
        ),
        migrations.CreateModel(
            name="VacancyBlackList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вакансия в черном списке",
                "verbose_name_plural": "Вакансии в черном списке",
            },
        ),
    ]
