# Generated by Django 4.1.5 on 2023-01-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0003_alter_vacancy_description_alter_vacancy_salary_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="url",
            field=models.URLField(),
        ),
    ]
